#pragma region Include

#pragma once

#include "Core_4_4.hpp"

#pragma endregion


#pragma region Macros

#pragma endregion


namespace GreatVEngine2
{
	namespace OpenGL
	{
		class Core_4_5:
			public virtual Core
		{
		protected:
			const PFNGLCLIPCONTROLPROC									glClipControl = nullptr;
			const PFNGLCREATETRANSFORMFEEDBACKSPROC						glCreateTransformFeedbacks = nullptr;
			const PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC					glTransformFeedbackBufferBase = nullptr;
			const PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC					glTransformFeedbackBufferRange = nullptr;
			const PFNGLGETTRANSFORMFEEDBACKIVPROC						glGetTransformFeedbackiv = nullptr;
			const PFNGLGETTRANSFORMFEEDBACKI_VPROC						glGetTransformFeedbacki_v = nullptr;
			const PFNGLGETTRANSFORMFEEDBACKI64_VPROC					glGetTransformFeedbacki64_v = nullptr;
			const PFNGLCREATEBUFFERSPROC								glCreateBuffers = nullptr;
			const PFNGLNAMEDBUFFERSTORAGEPROC							glNamedBufferStorage = nullptr;
			const PFNGLNAMEDBUFFERDATAPROC								glNamedBufferData = nullptr;
			const PFNGLNAMEDBUFFERSUBDATAPROC							glNamedBufferSubData = nullptr;
			const PFNGLCOPYNAMEDBUFFERSUBDATAPROC						glCopyNamedBufferSubData = nullptr;
			const PFNGLCLEARNAMEDBUFFERDATAPROC							glClearNamedBufferData = nullptr;
			const PFNGLCLEARNAMEDBUFFERSUBDATAPROC						glClearNamedBufferSubData = nullptr;
			const PFNGLMAPNAMEDBUFFERPROC								glMapNamedBuffer = nullptr;
			const PFNGLMAPNAMEDBUFFERRANGEPROC							glMapNamedBufferRange = nullptr;
			const PFNGLUNMAPNAMEDBUFFERPROC								glUnmapNamedBuffer = nullptr;
			const PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC					glFlushMappedNamedBufferRange = nullptr;
			const PFNGLGETNAMEDBUFFERPARAMETERIVPROC					glGetNamedBufferParameteriv = nullptr;
			const PFNGLGETNAMEDBUFFERPARAMETERI64VPROC					glGetNamedBufferParameteri64v = nullptr;
			const PFNGLGETNAMEDBUFFERPOINTERVPROC						glGetNamedBufferPointerv = nullptr;
			const PFNGLGETNAMEDBUFFERSUBDATAPROC						glGetNamedBufferSubData = nullptr;
			const PFNGLCREATEFRAMEBUFFERSPROC							glCreateFramebuffers = nullptr;
			const PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC					glNamedFramebufferRenderbuffer = nullptr;
			const PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC					glNamedFramebufferParameteri = nullptr;
			const PFNGLNAMEDFRAMEBUFFERTEXTUREPROC						glNamedFramebufferTexture = nullptr;
			const PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC					glNamedFramebufferTextureLayer = nullptr;
			const PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC					glNamedFramebufferDrawBuffer = nullptr;
			const PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC					glNamedFramebufferDrawBuffers = nullptr;
			const PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC					glNamedFramebufferReadBuffer = nullptr;
			const PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC				glInvalidateNamedFramebufferData = nullptr;
			const PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC			glInvalidateNamedFramebufferSubData = nullptr;
			const PFNGLCLEARNAMEDFRAMEBUFFERIVPROC						glClearNamedFramebufferiv = nullptr;
			const PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC						glClearNamedFramebufferuiv = nullptr;
			const PFNGLCLEARNAMEDFRAMEBUFFERFVPROC						glClearNamedFramebufferfv = nullptr;
			const PFNGLCLEARNAMEDFRAMEBUFFERFIPROC						glClearNamedFramebufferfi = nullptr;
			const PFNGLBLITNAMEDFRAMEBUFFERPROC							glBlitNamedFramebuffer = nullptr;
			const PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC					glCheckNamedFramebufferStatus = nullptr;
			const PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC				glGetNamedFramebufferParameteriv = nullptr;
			const PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC		glGetNamedFramebufferAttachmentParameteriv = nullptr;
			const PFNGLCREATERENDERBUFFERSPROC							glCreateRenderbuffers = nullptr;
			const PFNGLNAMEDRENDERBUFFERSTORAGEPROC						glNamedRenderbufferStorage = nullptr;
			const PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC			glNamedRenderbufferStorageMultisample = nullptr;
			const PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC				glGetNamedRenderbufferParameteriv = nullptr;
			const PFNGLCREATETEXTURESPROC								glCreateTextures = nullptr;
			const PFNGLTEXTUREBUFFERPROC								glTextureBuffer = nullptr;
			const PFNGLTEXTUREBUFFERRANGEPROC							glTextureBufferRange = nullptr;
			const PFNGLTEXTURESTORAGE1DPROC								glTextureStorage1D = nullptr;
			const PFNGLTEXTURESTORAGE2DPROC								glTextureStorage2D = nullptr;
			const PFNGLTEXTURESTORAGE3DPROC								glTextureStorage3D = nullptr;
			const PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC					glTextureStorage2DMultisample = nullptr;
			const PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC					glTextureStorage3DMultisample = nullptr;
			const PFNGLTEXTURESUBIMAGE1DPROC							glTextureSubImage1D = nullptr;
			const PFNGLTEXTURESUBIMAGE2DPROC							glTextureSubImage2D = nullptr;
			const PFNGLTEXTURESUBIMAGE3DPROC							glTextureSubImage3D = nullptr;
			const PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC					glCompressedTextureSubImage1D = nullptr;
			const PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC					glCompressedTextureSubImage2D = nullptr;
			const PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC					glCompressedTextureSubImage3D = nullptr;
			const PFNGLCOPYTEXTURESUBIMAGE1DPROC						glCopyTextureSubImage1D = nullptr;
			const PFNGLCOPYTEXTURESUBIMAGE2DPROC						glCopyTextureSubImage2D = nullptr;
			const PFNGLCOPYTEXTURESUBIMAGE3DPROC						glCopyTextureSubImage3D = nullptr;
			const PFNGLTEXTUREPARAMETERFPROC							glTextureParameterf = nullptr;
			const PFNGLTEXTUREPARAMETERFVPROC							glTextureParameterfv = nullptr;
			const PFNGLTEXTUREPARAMETERIPROC							glTextureParameteri = nullptr;
			const PFNGLTEXTUREPARAMETERIIVPROC							glTextureParameterIiv = nullptr;
			const PFNGLTEXTUREPARAMETERIUIVPROC							glTextureParameterIuiv = nullptr;
			const PFNGLTEXTUREPARAMETERIVPROC							glTextureParameteriv = nullptr;
			const PFNGLGENERATETEXTUREMIPMAPPROC						glGenerateTextureMipmap = nullptr;
			const PFNGLBINDTEXTUREUNITPROC								glBindTextureUnit = nullptr;
			const PFNGLGETTEXTUREIMAGEPROC								glGetTextureImage = nullptr;
			const PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC					glGetCompressedTextureImage = nullptr;
			const PFNGLGETTEXTURELEVELPARAMETERFVPROC					glGetTextureLevelParameterfv = nullptr;
			const PFNGLGETTEXTURELEVELPARAMETERIVPROC					glGetTextureLevelParameteriv = nullptr;
			const PFNGLGETTEXTUREPARAMETERFVPROC						glGetTextureParameterfv = nullptr;
			const PFNGLGETTEXTUREPARAMETERIIVPROC						glGetTextureParameterIiv = nullptr;
			const PFNGLGETTEXTUREPARAMETERIUIVPROC						glGetTextureParameterIuiv = nullptr;
			const PFNGLGETTEXTUREPARAMETERIVPROC						glGetTextureParameteriv = nullptr;
			const PFNGLCREATEVERTEXARRAYSPROC							glCreateVertexArrays = nullptr;
			const PFNGLDISABLEVERTEXARRAYATTRIBPROC						glDisableVertexArrayAttrib = nullptr;
			const PFNGLENABLEVERTEXARRAYATTRIBPROC						glEnableVertexArrayAttrib = nullptr;
			const PFNGLVERTEXARRAYELEMENTBUFFERPROC						glVertexArrayElementBuffer = nullptr;
			const PFNGLVERTEXARRAYVERTEXBUFFERPROC						glVertexArrayVertexBuffer = nullptr;
			const PFNGLVERTEXARRAYVERTEXBUFFERSPROC						glVertexArrayVertexBuffers = nullptr;
			const PFNGLVERTEXARRAYATTRIBBINDINGPROC						glVertexArrayAttribBinding = nullptr;
			const PFNGLVERTEXARRAYATTRIBFORMATPROC						glVertexArrayAttribFormat = nullptr;
			const PFNGLVERTEXARRAYATTRIBIFORMATPROC						glVertexArrayAttribIFormat = nullptr;
			const PFNGLVERTEXARRAYATTRIBLFORMATPROC						glVertexArrayAttribLFormat = nullptr;
			const PFNGLVERTEXARRAYBINDINGDIVISORPROC					glVertexArrayBindingDivisor = nullptr;
			const PFNGLGETVERTEXARRAYIVPROC								glGetVertexArrayiv = nullptr;
			const PFNGLGETVERTEXARRAYINDEXEDIVPROC						glGetVertexArrayIndexediv = nullptr;
			const PFNGLGETVERTEXARRAYINDEXED64IVPROC					glGetVertexArrayIndexed64iv = nullptr;
			const PFNGLCREATESAMPLERSPROC								glCreateSamplers = nullptr;
			const PFNGLCREATEPROGRAMPIPELINESPROC						glCreateProgramPipelines = nullptr;
			const PFNGLCREATEQUERIESPROC								glCreateQueries = nullptr;
			const PFNGLGETQUERYBUFFEROBJECTI64VPROC						glGetQueryBufferObjecti64v = nullptr;
			const PFNGLGETQUERYBUFFEROBJECTIVPROC						glGetQueryBufferObjectiv = nullptr;
			const PFNGLGETQUERYBUFFEROBJECTUI64VPROC					glGetQueryBufferObjectui64v = nullptr;
			const PFNGLGETQUERYBUFFEROBJECTUIVPROC						glGetQueryBufferObjectuiv = nullptr;
			const PFNGLMEMORYBARRIERBYREGIONPROC						glMemoryBarrierByRegion = nullptr;
			const PFNGLGETTEXTURESUBIMAGEPROC							glGetTextureSubImage = nullptr;
			const PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC					glGetCompressedTextureSubImage = nullptr;
			const PFNGLGETGRAPHICSRESETSTATUSPROC						glGetGraphicsResetStatus = nullptr;
			const PFNGLGETNCOMPRESSEDTEXIMAGEPROC						glGetnCompressedTexImage = nullptr;
			const PFNGLGETNTEXIMAGEPROC									glGetnTexImage = nullptr;
			const PFNGLGETNUNIFORMDVPROC								glGetnUniformdv = nullptr;
			const PFNGLGETNUNIFORMFVPROC								glGetnUniformfv = nullptr;
			const PFNGLGETNUNIFORMIVPROC								glGetnUniformiv = nullptr;
			const PFNGLGETNUNIFORMUIVPROC								glGetnUniformuiv = nullptr;
			const PFNGLREADNPIXELSPROC									glReadnPixels = nullptr;
			const PFNGLGETNMAPDVPROC									glGetnMapdv = nullptr;
			const PFNGLGETNMAPFVPROC									glGetnMapfv = nullptr;
			const PFNGLGETNMAPIVPROC									glGetnMapiv = nullptr;
			const PFNGLGETNPIXELMAPFVPROC								glGetnPixelMapfv = nullptr;
			const PFNGLGETNPIXELMAPUIVPROC								glGetnPixelMapuiv = nullptr;
			const PFNGLGETNPIXELMAPUSVPROC								glGetnPixelMapusv = nullptr;
			const PFNGLGETNPOLYGONSTIPPLEPROC							glGetnPolygonStipple = nullptr;
			const PFNGLGETNCOLORTABLEPROC								glGetnColorTable = nullptr;
			const PFNGLGETNCONVOLUTIONFILTERPROC						glGetnConvolutionFilter = nullptr;
			const PFNGLGETNSEPARABLEFILTERPROC							glGetnSeparableFilter = nullptr;
			const PFNGLGETNHISTOGRAMPROC								glGetnHistogram = nullptr;
			const PFNGLGETNMINMAXPROC									glGetnMinmax = nullptr;
			const PFNGLTEXTUREBARRIERPROC								glTextureBarrier = nullptr;
		protected:
			inline Core_4_5() = default;
			inline Core_4_5(
				const PFNGLCLIPCONTROLPROC&									glClipControl_,
				const PFNGLCREATETRANSFORMFEEDBACKSPROC&					glCreateTransformFeedbacks_,
				const PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC&					glTransformFeedbackBufferBase_,
				const PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC&				glTransformFeedbackBufferRange_,
				const PFNGLGETTRANSFORMFEEDBACKIVPROC&						glGetTransformFeedbackiv_,
				const PFNGLGETTRANSFORMFEEDBACKI_VPROC&						glGetTransformFeedbacki_v_,
				const PFNGLGETTRANSFORMFEEDBACKI64_VPROC&					glGetTransformFeedbacki64_v_,
				const PFNGLCREATEBUFFERSPROC&								glCreateBuffers_,
				const PFNGLNAMEDBUFFERSTORAGEPROC&							glNamedBufferStorage_,
				const PFNGLNAMEDBUFFERDATAPROC&								glNamedBufferData_,
				const PFNGLNAMEDBUFFERSUBDATAPROC&							glNamedBufferSubData_,
				const PFNGLCOPYNAMEDBUFFERSUBDATAPROC&						glCopyNamedBufferSubData_,
				const PFNGLCLEARNAMEDBUFFERDATAPROC&						glClearNamedBufferData_,
				const PFNGLCLEARNAMEDBUFFERSUBDATAPROC&						glClearNamedBufferSubData_,
				const PFNGLMAPNAMEDBUFFERPROC&								glMapNamedBuffer_,
				const PFNGLMAPNAMEDBUFFERRANGEPROC&							glMapNamedBufferRange_,
				const PFNGLUNMAPNAMEDBUFFERPROC&							glUnmapNamedBuffer_,
				const PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC&					glFlushMappedNamedBufferRange_,
				const PFNGLGETNAMEDBUFFERPARAMETERIVPROC&					glGetNamedBufferParameteriv_,
				const PFNGLGETNAMEDBUFFERPARAMETERI64VPROC&					glGetNamedBufferParameteri64v_,
				const PFNGLGETNAMEDBUFFERPOINTERVPROC&						glGetNamedBufferPointerv_,
				const PFNGLGETNAMEDBUFFERSUBDATAPROC&						glGetNamedBufferSubData_,
				const PFNGLCREATEFRAMEBUFFERSPROC&							glCreateFramebuffers_,
				const PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC&				glNamedFramebufferRenderbuffer_,
				const PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC&					glNamedFramebufferParameteri_,
				const PFNGLNAMEDFRAMEBUFFERTEXTUREPROC&						glNamedFramebufferTexture_,
				const PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC&				glNamedFramebufferTextureLayer_,
				const PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC&					glNamedFramebufferDrawBuffer_,
				const PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC&					glNamedFramebufferDrawBuffers_,
				const PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC&					glNamedFramebufferReadBuffer_,
				const PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC&				glInvalidateNamedFramebufferData_,
				const PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC&			glInvalidateNamedFramebufferSubData_,
				const PFNGLCLEARNAMEDFRAMEBUFFERIVPROC&						glClearNamedFramebufferiv_,
				const PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC&					glClearNamedFramebufferuiv_,
				const PFNGLCLEARNAMEDFRAMEBUFFERFVPROC&						glClearNamedFramebufferfv_,
				const PFNGLCLEARNAMEDFRAMEBUFFERFIPROC&						glClearNamedFramebufferfi_,
				const PFNGLBLITNAMEDFRAMEBUFFERPROC&						glBlitNamedFramebuffer_,
				const PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC&					glCheckNamedFramebufferStatus_,
				const PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC&				glGetNamedFramebufferParameteriv_,
				const PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC&	glGetNamedFramebufferAttachmentParameteriv_,
				const PFNGLCREATERENDERBUFFERSPROC&							glCreateRenderbuffers_,
				const PFNGLNAMEDRENDERBUFFERSTORAGEPROC&					glNamedRenderbufferStorage_,
				const PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC&			glNamedRenderbufferStorageMultisample_,
				const PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC&				glGetNamedRenderbufferParameteriv_,
				const PFNGLCREATETEXTURESPROC&								glCreateTextures_,
				const PFNGLTEXTUREBUFFERPROC&								glTextureBuffer_,
				const PFNGLTEXTUREBUFFERRANGEPROC&							glTextureBufferRange_,
				const PFNGLTEXTURESTORAGE1DPROC&							glTextureStorage1D_,
				const PFNGLTEXTURESTORAGE2DPROC&							glTextureStorage2D_,
				const PFNGLTEXTURESTORAGE3DPROC&							glTextureStorage3D_,
				const PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC&					glTextureStorage2DMultisample_,
				const PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC&					glTextureStorage3DMultisample_,
				const PFNGLTEXTURESUBIMAGE1DPROC&							glTextureSubImage1D_,
				const PFNGLTEXTURESUBIMAGE2DPROC&							glTextureSubImage2D_,
				const PFNGLTEXTURESUBIMAGE3DPROC&							glTextureSubImage3D_,
				const PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC&					glCompressedTextureSubImage1D_,
				const PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC&					glCompressedTextureSubImage2D_,
				const PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC&					glCompressedTextureSubImage3D_,
				const PFNGLCOPYTEXTURESUBIMAGE1DPROC&						glCopyTextureSubImage1D_,
				const PFNGLCOPYTEXTURESUBIMAGE2DPROC&						glCopyTextureSubImage2D_,
				const PFNGLCOPYTEXTURESUBIMAGE3DPROC&						glCopyTextureSubImage3D_,
				const PFNGLTEXTUREPARAMETERFPROC&							glTextureParameterf_,
				const PFNGLTEXTUREPARAMETERFVPROC&							glTextureParameterfv_,
				const PFNGLTEXTUREPARAMETERIPROC&							glTextureParameteri_,
				const PFNGLTEXTUREPARAMETERIIVPROC&							glTextureParameterIiv_,
				const PFNGLTEXTUREPARAMETERIUIVPROC&						glTextureParameterIuiv_,
				const PFNGLTEXTUREPARAMETERIVPROC&							glTextureParameteriv_,
				const PFNGLGENERATETEXTUREMIPMAPPROC&						glGenerateTextureMipmap_,
				const PFNGLBINDTEXTUREUNITPROC&								glBindTextureUnit_,
				const PFNGLGETTEXTUREIMAGEPROC&								glGetTextureImage_,
				const PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC&					glGetCompressedTextureImage_,
				const PFNGLGETTEXTURELEVELPARAMETERFVPROC&					glGetTextureLevelParameterfv_,
				const PFNGLGETTEXTURELEVELPARAMETERIVPROC&					glGetTextureLevelParameteriv_,
				const PFNGLGETTEXTUREPARAMETERFVPROC&						glGetTextureParameterfv_,
				const PFNGLGETTEXTUREPARAMETERIIVPROC&						glGetTextureParameterIiv_,
				const PFNGLGETTEXTUREPARAMETERIUIVPROC&						glGetTextureParameterIuiv_,
				const PFNGLGETTEXTUREPARAMETERIVPROC&						glGetTextureParameteriv_,
				const PFNGLCREATEVERTEXARRAYSPROC&							glCreateVertexArrays_,
				const PFNGLDISABLEVERTEXARRAYATTRIBPROC&					glDisableVertexArrayAttrib_,
				const PFNGLENABLEVERTEXARRAYATTRIBPROC&						glEnableVertexArrayAttrib_,
				const PFNGLVERTEXARRAYELEMENTBUFFERPROC&					glVertexArrayElementBuffer_,
				const PFNGLVERTEXARRAYVERTEXBUFFERPROC&						glVertexArrayVertexBuffer_,
				const PFNGLVERTEXARRAYVERTEXBUFFERSPROC&					glVertexArrayVertexBuffers_,
				const PFNGLVERTEXARRAYATTRIBBINDINGPROC&					glVertexArrayAttribBinding_,
				const PFNGLVERTEXARRAYATTRIBFORMATPROC&						glVertexArrayAttribFormat_,
				const PFNGLVERTEXARRAYATTRIBIFORMATPROC&					glVertexArrayAttribIFormat_,
				const PFNGLVERTEXARRAYATTRIBLFORMATPROC&					glVertexArrayAttribLFormat_,
				const PFNGLVERTEXARRAYBINDINGDIVISORPROC&					glVertexArrayBindingDivisor_,
				const PFNGLGETVERTEXARRAYIVPROC&							glGetVertexArrayiv_,
				const PFNGLGETVERTEXARRAYINDEXEDIVPROC&						glGetVertexArrayIndexediv_,
				const PFNGLGETVERTEXARRAYINDEXED64IVPROC&					glGetVertexArrayIndexed64iv_,
				const PFNGLCREATESAMPLERSPROC&								glCreateSamplers_,
				const PFNGLCREATEPROGRAMPIPELINESPROC&						glCreateProgramPipelines_,
				const PFNGLCREATEQUERIESPROC&								glCreateQueries_,
				const PFNGLGETQUERYBUFFEROBJECTI64VPROC&					glGetQueryBufferObjecti64v_,
				const PFNGLGETQUERYBUFFEROBJECTIVPROC&						glGetQueryBufferObjectiv_,
				const PFNGLGETQUERYBUFFEROBJECTUI64VPROC&					glGetQueryBufferObjectui64v_,
				const PFNGLGETQUERYBUFFEROBJECTUIVPROC&						glGetQueryBufferObjectuiv_,
				const PFNGLMEMORYBARRIERBYREGIONPROC&						glMemoryBarrierByRegion_,
				const PFNGLGETTEXTURESUBIMAGEPROC&							glGetTextureSubImage_,
				const PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC&				glGetCompressedTextureSubImage_,
				const PFNGLGETGRAPHICSRESETSTATUSPROC&						glGetGraphicsResetStatus_,
				const PFNGLGETNCOMPRESSEDTEXIMAGEPROC&						glGetnCompressedTexImage_,
				const PFNGLGETNTEXIMAGEPROC&								glGetnTexImage_,
				const PFNGLGETNUNIFORMDVPROC&								glGetnUniformdv_,
				const PFNGLGETNUNIFORMFVPROC&								glGetnUniformfv_,
				const PFNGLGETNUNIFORMIVPROC&								glGetnUniformiv_,
				const PFNGLGETNUNIFORMUIVPROC&								glGetnUniformuiv_,
				const PFNGLREADNPIXELSPROC&									glReadnPixels_,
				const PFNGLGETNMAPDVPROC&									glGetnMapdv_,
				const PFNGLGETNMAPFVPROC&									glGetnMapfv_,
				const PFNGLGETNMAPIVPROC&									glGetnMapiv_,
				const PFNGLGETNPIXELMAPFVPROC&								glGetnPixelMapfv_,
				const PFNGLGETNPIXELMAPUIVPROC&								glGetnPixelMapuiv_,
				const PFNGLGETNPIXELMAPUSVPROC&								glGetnPixelMapusv_,
				const PFNGLGETNPOLYGONSTIPPLEPROC&							glGetnPolygonStipple_,
				const PFNGLGETNCOLORTABLEPROC&								glGetnColorTable_,
				const PFNGLGETNCONVOLUTIONFILTERPROC&						glGetnConvolutionFilter_,
				const PFNGLGETNSEPARABLEFILTERPROC&							glGetnSeparableFilter_,
				const PFNGLGETNHISTOGRAMPROC&								glGetnHistogram_,
				const PFNGLGETNMINMAXPROC&									glGetnMinmax_,
				const PFNGLTEXTUREBARRIERPROC&								glTextureBarrier_
				);
		};
#pragma region Core_4_5
		Core_4_5::Core_4_5(
			const PFNGLCLIPCONTROLPROC&									glClipControl_,
			const PFNGLCREATETRANSFORMFEEDBACKSPROC&					glCreateTransformFeedbacks_,
			const PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC&					glTransformFeedbackBufferBase_,
			const PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC&				glTransformFeedbackBufferRange_,
			const PFNGLGETTRANSFORMFEEDBACKIVPROC&						glGetTransformFeedbackiv_,
			const PFNGLGETTRANSFORMFEEDBACKI_VPROC&						glGetTransformFeedbacki_v_,
			const PFNGLGETTRANSFORMFEEDBACKI64_VPROC&					glGetTransformFeedbacki64_v_,
			const PFNGLCREATEBUFFERSPROC&								glCreateBuffers_,
			const PFNGLNAMEDBUFFERSTORAGEPROC&							glNamedBufferStorage_,
			const PFNGLNAMEDBUFFERDATAPROC&								glNamedBufferData_,
			const PFNGLNAMEDBUFFERSUBDATAPROC&							glNamedBufferSubData_,
			const PFNGLCOPYNAMEDBUFFERSUBDATAPROC&						glCopyNamedBufferSubData_,
			const PFNGLCLEARNAMEDBUFFERDATAPROC&						glClearNamedBufferData_,
			const PFNGLCLEARNAMEDBUFFERSUBDATAPROC&						glClearNamedBufferSubData_,
			const PFNGLMAPNAMEDBUFFERPROC&								glMapNamedBuffer_,
			const PFNGLMAPNAMEDBUFFERRANGEPROC&							glMapNamedBufferRange_,
			const PFNGLUNMAPNAMEDBUFFERPROC&							glUnmapNamedBuffer_,
			const PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC&					glFlushMappedNamedBufferRange_,
			const PFNGLGETNAMEDBUFFERPARAMETERIVPROC&					glGetNamedBufferParameteriv_,
			const PFNGLGETNAMEDBUFFERPARAMETERI64VPROC&					glGetNamedBufferParameteri64v_,
			const PFNGLGETNAMEDBUFFERPOINTERVPROC&						glGetNamedBufferPointerv_,
			const PFNGLGETNAMEDBUFFERSUBDATAPROC&						glGetNamedBufferSubData_,
			const PFNGLCREATEFRAMEBUFFERSPROC&							glCreateFramebuffers_,
			const PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC&				glNamedFramebufferRenderbuffer_,
			const PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC&					glNamedFramebufferParameteri_,
			const PFNGLNAMEDFRAMEBUFFERTEXTUREPROC&						glNamedFramebufferTexture_,
			const PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC&				glNamedFramebufferTextureLayer_,
			const PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC&					glNamedFramebufferDrawBuffer_,
			const PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC&					glNamedFramebufferDrawBuffers_,
			const PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC&					glNamedFramebufferReadBuffer_,
			const PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC&				glInvalidateNamedFramebufferData_,
			const PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC&			glInvalidateNamedFramebufferSubData_,
			const PFNGLCLEARNAMEDFRAMEBUFFERIVPROC&						glClearNamedFramebufferiv_,
			const PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC&					glClearNamedFramebufferuiv_,
			const PFNGLCLEARNAMEDFRAMEBUFFERFVPROC&						glClearNamedFramebufferfv_,
			const PFNGLCLEARNAMEDFRAMEBUFFERFIPROC&						glClearNamedFramebufferfi_,
			const PFNGLBLITNAMEDFRAMEBUFFERPROC&						glBlitNamedFramebuffer_,
			const PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC&					glCheckNamedFramebufferStatus_,
			const PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC&				glGetNamedFramebufferParameteriv_,
			const PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC&	glGetNamedFramebufferAttachmentParameteriv_,
			const PFNGLCREATERENDERBUFFERSPROC&							glCreateRenderbuffers_,
			const PFNGLNAMEDRENDERBUFFERSTORAGEPROC&					glNamedRenderbufferStorage_,
			const PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC&			glNamedRenderbufferStorageMultisample_,
			const PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC&				glGetNamedRenderbufferParameteriv_,
			const PFNGLCREATETEXTURESPROC&								glCreateTextures_,
			const PFNGLTEXTUREBUFFERPROC&								glTextureBuffer_,
			const PFNGLTEXTUREBUFFERRANGEPROC&							glTextureBufferRange_,
			const PFNGLTEXTURESTORAGE1DPROC&							glTextureStorage1D_,
			const PFNGLTEXTURESTORAGE2DPROC&							glTextureStorage2D_,
			const PFNGLTEXTURESTORAGE3DPROC&							glTextureStorage3D_,
			const PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC&					glTextureStorage2DMultisample_,
			const PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC&					glTextureStorage3DMultisample_,
			const PFNGLTEXTURESUBIMAGE1DPROC&							glTextureSubImage1D_,
			const PFNGLTEXTURESUBIMAGE2DPROC&							glTextureSubImage2D_,
			const PFNGLTEXTURESUBIMAGE3DPROC&							glTextureSubImage3D_,
			const PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC&					glCompressedTextureSubImage1D_,
			const PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC&					glCompressedTextureSubImage2D_,
			const PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC&					glCompressedTextureSubImage3D_,
			const PFNGLCOPYTEXTURESUBIMAGE1DPROC&						glCopyTextureSubImage1D_,
			const PFNGLCOPYTEXTURESUBIMAGE2DPROC&						glCopyTextureSubImage2D_,
			const PFNGLCOPYTEXTURESUBIMAGE3DPROC&						glCopyTextureSubImage3D_,
			const PFNGLTEXTUREPARAMETERFPROC&							glTextureParameterf_,
			const PFNGLTEXTUREPARAMETERFVPROC&							glTextureParameterfv_,
			const PFNGLTEXTUREPARAMETERIPROC&							glTextureParameteri_,
			const PFNGLTEXTUREPARAMETERIIVPROC&							glTextureParameterIiv_,
			const PFNGLTEXTUREPARAMETERIUIVPROC&						glTextureParameterIuiv_,
			const PFNGLTEXTUREPARAMETERIVPROC&							glTextureParameteriv_,
			const PFNGLGENERATETEXTUREMIPMAPPROC&						glGenerateTextureMipmap_,
			const PFNGLBINDTEXTUREUNITPROC&								glBindTextureUnit_,
			const PFNGLGETTEXTUREIMAGEPROC&								glGetTextureImage_,
			const PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC&					glGetCompressedTextureImage_,
			const PFNGLGETTEXTURELEVELPARAMETERFVPROC&					glGetTextureLevelParameterfv_,
			const PFNGLGETTEXTURELEVELPARAMETERIVPROC&					glGetTextureLevelParameteriv_,
			const PFNGLGETTEXTUREPARAMETERFVPROC&						glGetTextureParameterfv_,
			const PFNGLGETTEXTUREPARAMETERIIVPROC&						glGetTextureParameterIiv_,
			const PFNGLGETTEXTUREPARAMETERIUIVPROC&						glGetTextureParameterIuiv_,
			const PFNGLGETTEXTUREPARAMETERIVPROC&						glGetTextureParameteriv_,
			const PFNGLCREATEVERTEXARRAYSPROC&							glCreateVertexArrays_,
			const PFNGLDISABLEVERTEXARRAYATTRIBPROC&					glDisableVertexArrayAttrib_,
			const PFNGLENABLEVERTEXARRAYATTRIBPROC&						glEnableVertexArrayAttrib_,
			const PFNGLVERTEXARRAYELEMENTBUFFERPROC&					glVertexArrayElementBuffer_,
			const PFNGLVERTEXARRAYVERTEXBUFFERPROC&						glVertexArrayVertexBuffer_,
			const PFNGLVERTEXARRAYVERTEXBUFFERSPROC&					glVertexArrayVertexBuffers_,
			const PFNGLVERTEXARRAYATTRIBBINDINGPROC&					glVertexArrayAttribBinding_,
			const PFNGLVERTEXARRAYATTRIBFORMATPROC&						glVertexArrayAttribFormat_,
			const PFNGLVERTEXARRAYATTRIBIFORMATPROC&					glVertexArrayAttribIFormat_,
			const PFNGLVERTEXARRAYATTRIBLFORMATPROC&					glVertexArrayAttribLFormat_,
			const PFNGLVERTEXARRAYBINDINGDIVISORPROC&					glVertexArrayBindingDivisor_,
			const PFNGLGETVERTEXARRAYIVPROC&							glGetVertexArrayiv_,
			const PFNGLGETVERTEXARRAYINDEXEDIVPROC&						glGetVertexArrayIndexediv_,
			const PFNGLGETVERTEXARRAYINDEXED64IVPROC&					glGetVertexArrayIndexed64iv_,
			const PFNGLCREATESAMPLERSPROC&								glCreateSamplers_,
			const PFNGLCREATEPROGRAMPIPELINESPROC&						glCreateProgramPipelines_,
			const PFNGLCREATEQUERIESPROC&								glCreateQueries_,
			const PFNGLGETQUERYBUFFEROBJECTI64VPROC&					glGetQueryBufferObjecti64v_,
			const PFNGLGETQUERYBUFFEROBJECTIVPROC&						glGetQueryBufferObjectiv_,
			const PFNGLGETQUERYBUFFEROBJECTUI64VPROC&					glGetQueryBufferObjectui64v_,
			const PFNGLGETQUERYBUFFEROBJECTUIVPROC&						glGetQueryBufferObjectuiv_,
			const PFNGLMEMORYBARRIERBYREGIONPROC&						glMemoryBarrierByRegion_,
			const PFNGLGETTEXTURESUBIMAGEPROC&							glGetTextureSubImage_,
			const PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC&				glGetCompressedTextureSubImage_,
			const PFNGLGETGRAPHICSRESETSTATUSPROC&						glGetGraphicsResetStatus_,
			const PFNGLGETNCOMPRESSEDTEXIMAGEPROC&						glGetnCompressedTexImage_,
			const PFNGLGETNTEXIMAGEPROC&								glGetnTexImage_,
			const PFNGLGETNUNIFORMDVPROC&								glGetnUniformdv_,
			const PFNGLGETNUNIFORMFVPROC&								glGetnUniformfv_,
			const PFNGLGETNUNIFORMIVPROC&								glGetnUniformiv_,
			const PFNGLGETNUNIFORMUIVPROC&								glGetnUniformuiv_,
			const PFNGLREADNPIXELSPROC&									glReadnPixels_,
			const PFNGLGETNMAPDVPROC&									glGetnMapdv_,
			const PFNGLGETNMAPFVPROC&									glGetnMapfv_,
			const PFNGLGETNMAPIVPROC&									glGetnMapiv_,
			const PFNGLGETNPIXELMAPFVPROC&								glGetnPixelMapfv_,
			const PFNGLGETNPIXELMAPUIVPROC&								glGetnPixelMapuiv_,
			const PFNGLGETNPIXELMAPUSVPROC&								glGetnPixelMapusv_,
			const PFNGLGETNPOLYGONSTIPPLEPROC&							glGetnPolygonStipple_,
			const PFNGLGETNCOLORTABLEPROC&								glGetnColorTable_,
			const PFNGLGETNCONVOLUTIONFILTERPROC&						glGetnConvolutionFilter_,
			const PFNGLGETNSEPARABLEFILTERPROC&							glGetnSeparableFilter_,
			const PFNGLGETNHISTOGRAMPROC&								glGetnHistogram_,
			const PFNGLGETNMINMAXPROC&									glGetnMinmax_,
			const PFNGLTEXTUREBARRIERPROC&								glTextureBarrier_
			):
		glClipControl(glClipControl_),
			glCreateTransformFeedbacks(glCreateTransformFeedbacks_),
			glTransformFeedbackBufferBase(glTransformFeedbackBufferBase_),
			glTransformFeedbackBufferRange(glTransformFeedbackBufferRange_),
			glGetTransformFeedbackiv(glGetTransformFeedbackiv_),
			glGetTransformFeedbacki_v(glGetTransformFeedbacki_v_),
			glGetTransformFeedbacki64_v(glGetTransformFeedbacki64_v_),
			glCreateBuffers(glCreateBuffers_),
			glNamedBufferStorage(glNamedBufferStorage_),
			glNamedBufferData(glNamedBufferData_),
			glNamedBufferSubData(glNamedBufferSubData_),
			glCopyNamedBufferSubData(glCopyNamedBufferSubData_),
			glClearNamedBufferData(glClearNamedBufferData_),
			glClearNamedBufferSubData(glClearNamedBufferSubData_),
			glMapNamedBuffer(glMapNamedBuffer_),
			glMapNamedBufferRange(glMapNamedBufferRange_),
			glUnmapNamedBuffer(glUnmapNamedBuffer_),
			glFlushMappedNamedBufferRange(glFlushMappedNamedBufferRange_),
			glGetNamedBufferParameteriv(glGetNamedBufferParameteriv_),
			glGetNamedBufferParameteri64v(glGetNamedBufferParameteri64v_),
			glGetNamedBufferPointerv(glGetNamedBufferPointerv_),
			glGetNamedBufferSubData(glGetNamedBufferSubData_),
			glCreateFramebuffers(glCreateFramebuffers_),
			glNamedFramebufferRenderbuffer(glNamedFramebufferRenderbuffer_),
			glNamedFramebufferParameteri(glNamedFramebufferParameteri_),
			glNamedFramebufferTexture(glNamedFramebufferTexture_),
			glNamedFramebufferTextureLayer(glNamedFramebufferTextureLayer_),
			glNamedFramebufferDrawBuffer(glNamedFramebufferDrawBuffer_),
			glNamedFramebufferDrawBuffers(glNamedFramebufferDrawBuffers_),
			glNamedFramebufferReadBuffer(glNamedFramebufferReadBuffer_),
			glInvalidateNamedFramebufferData(glInvalidateNamedFramebufferData_),
			glInvalidateNamedFramebufferSubData(glInvalidateNamedFramebufferSubData_),
			glClearNamedFramebufferiv(glClearNamedFramebufferiv_),
			glClearNamedFramebufferuiv(glClearNamedFramebufferuiv_),
			glClearNamedFramebufferfv(glClearNamedFramebufferfv_),
			glClearNamedFramebufferfi(glClearNamedFramebufferfi_),
			glBlitNamedFramebuffer(glBlitNamedFramebuffer_),
			glCheckNamedFramebufferStatus(glCheckNamedFramebufferStatus_),
			glGetNamedFramebufferParameteriv(glGetNamedFramebufferParameteriv_),
			glGetNamedFramebufferAttachmentParameteriv(glGetNamedFramebufferAttachmentParameteriv_),
			glCreateRenderbuffers(glCreateRenderbuffers_),
			glNamedRenderbufferStorage(glNamedRenderbufferStorage_),
			glNamedRenderbufferStorageMultisample(glNamedRenderbufferStorageMultisample_),
			glGetNamedRenderbufferParameteriv(glGetNamedRenderbufferParameteriv_),
			glCreateTextures(glCreateTextures_),
			glTextureBuffer(glTextureBuffer_),
			glTextureBufferRange(glTextureBufferRange_),
			glTextureStorage1D(glTextureStorage1D_),
			glTextureStorage2D(glTextureStorage2D_),
			glTextureStorage3D(glTextureStorage3D_),
			glTextureStorage2DMultisample(glTextureStorage2DMultisample_),
			glTextureStorage3DMultisample(glTextureStorage3DMultisample_),
			glTextureSubImage1D(glTextureSubImage1D_),
			glTextureSubImage2D(glTextureSubImage2D_),
			glTextureSubImage3D(glTextureSubImage3D_),
			glCompressedTextureSubImage1D(glCompressedTextureSubImage1D_),
			glCompressedTextureSubImage2D(glCompressedTextureSubImage2D_),
			glCompressedTextureSubImage3D(glCompressedTextureSubImage3D_),
			glCopyTextureSubImage1D(glCopyTextureSubImage1D_),
			glCopyTextureSubImage2D(glCopyTextureSubImage2D_),
			glCopyTextureSubImage3D(glCopyTextureSubImage3D_),
			glTextureParameterf(glTextureParameterf_),
			glTextureParameterfv(glTextureParameterfv_),
			glTextureParameteri(glTextureParameteri_),
			glTextureParameterIiv(glTextureParameterIiv_),
			glTextureParameterIuiv(glTextureParameterIuiv_),
			glTextureParameteriv(glTextureParameteriv_),
			glGenerateTextureMipmap(glGenerateTextureMipmap_),
			glBindTextureUnit(glBindTextureUnit_),
			glGetTextureImage(glGetTextureImage_),
			glGetCompressedTextureImage(glGetCompressedTextureImage_),
			glGetTextureLevelParameterfv(glGetTextureLevelParameterfv_),
			glGetTextureLevelParameteriv(glGetTextureLevelParameteriv_),
			glGetTextureParameterfv(glGetTextureParameterfv_),
			glGetTextureParameterIiv(glGetTextureParameterIiv_),
			glGetTextureParameterIuiv(glGetTextureParameterIuiv_),
			glGetTextureParameteriv(glGetTextureParameteriv_),
			glCreateVertexArrays(glCreateVertexArrays_),
			glDisableVertexArrayAttrib(glDisableVertexArrayAttrib_),
			glEnableVertexArrayAttrib(glEnableVertexArrayAttrib_),
			glVertexArrayElementBuffer(glVertexArrayElementBuffer_),
			glVertexArrayVertexBuffer(glVertexArrayVertexBuffer_),
			glVertexArrayVertexBuffers(glVertexArrayVertexBuffers_),
			glVertexArrayAttribBinding(glVertexArrayAttribBinding_),
			glVertexArrayAttribFormat(glVertexArrayAttribFormat_),
			glVertexArrayAttribIFormat(glVertexArrayAttribIFormat_),
			glVertexArrayAttribLFormat(glVertexArrayAttribLFormat_),
			glVertexArrayBindingDivisor(glVertexArrayBindingDivisor_),
			glGetVertexArrayiv(glGetVertexArrayiv_),
			glGetVertexArrayIndexediv(glGetVertexArrayIndexediv_),
			glGetVertexArrayIndexed64iv(glGetVertexArrayIndexed64iv_),
			glCreateSamplers(glCreateSamplers_),
			glCreateProgramPipelines(glCreateProgramPipelines_),
			glCreateQueries(glCreateQueries_),
			glGetQueryBufferObjecti64v(glGetQueryBufferObjecti64v_),
			glGetQueryBufferObjectiv(glGetQueryBufferObjectiv_),
			glGetQueryBufferObjectui64v(glGetQueryBufferObjectui64v_),
			glGetQueryBufferObjectuiv(glGetQueryBufferObjectuiv_),
			glMemoryBarrierByRegion(glMemoryBarrierByRegion_),
			glGetTextureSubImage(glGetTextureSubImage_),
			glGetCompressedTextureSubImage(glGetCompressedTextureSubImage_),
			glGetGraphicsResetStatus(glGetGraphicsResetStatus_),
			glGetnCompressedTexImage(glGetnCompressedTexImage_),
			glGetnTexImage(glGetnTexImage_),
			glGetnUniformdv(glGetnUniformdv_),
			glGetnUniformfv(glGetnUniformfv_),
			glGetnUniformiv(glGetnUniformiv_),
			glGetnUniformuiv(glGetnUniformuiv_),
			glReadnPixels(glReadnPixels_),
			glGetnMapdv(glGetnMapdv_),
			glGetnMapfv(glGetnMapfv_),
			glGetnMapiv(glGetnMapiv_),
			glGetnPixelMapfv(glGetnPixelMapfv_),
			glGetnPixelMapuiv(glGetnPixelMapuiv_),
			glGetnPixelMapusv(glGetnPixelMapusv_),
			glGetnPolygonStipple(glGetnPolygonStipple_),
			glGetnColorTable(glGetnColorTable_),
			glGetnConvolutionFilter(glGetnConvolutionFilter_),
			glGetnSeparableFilter(glGetnSeparableFilter_),
			glGetnHistogram(glGetnHistogram_),
			glGetnMinmax(glGetnMinmax_),
			glTextureBarrier(glTextureBarrier_)
		{
		}
#pragma endregion

		class Context_4_5:
			public Context_4_4,
			public virtual Core_4_5
		{
		};
#pragma region Context_4_5
#pragma endregion

		namespace OSs
		{
#if __GREAT_V_ENGINE_2__PLATFORM__ == __GREAT_V_ENGINE_2__PLATFORM_WINDOWS__
			namespace Windows
			{
				class Context_4_5:
					public Context_4_4,
					public OpenGL::Context_4_5
				{
				protected:
					inline static Attributes GetAttributes();
				private:
					inline Context_4_5(const Handle& handle_);
				protected:
					inline Context_4_5(const Handle& handle_, const EmptyTag&);
				public:
					inline Context_4_5(const DeviceContextHandle& deviceContextHandle_);
				};
#pragma region Context_4_5
				Context_4_5::Attributes Context_4_5::GetAttributes()
				{
					return{
						WGL_CONTEXT_MAJOR_VERSION_ARB, 4,
						WGL_CONTEXT_MINOR_VERSION_ARB, 5,
						WGL_CONTEXT_FLAGS_ARB, 0, // WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB (???) | WGL_CONTEXT_DEBUG_BIT_ARB
						WGL_CONTEXT_PROFILE_MASK_ARB, WGL_CONTEXT_CORE_PROFILE_BIT_ARB, // WGL_CONTEXT_CORE_PROFILE_BIT_ARB / WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB
						0, 0,
					};
				}

				Context_4_5::Context_4_5(const Handle& handle_, const EmptyTag&):
					Windows::Context_4_4(handle_, EmptyTag()),
					OpenGL::Context_4_5(),
					Core_1_2(),
					Core_1_3(),
					Core_1_4(),
					Core_1_5(),
					Core_2_0(),
					Core_2_1(),
					Core_3_0(),
					Core_3_1(),
					Core_3_2(),
					Core_3_3(),
					Core_4_0(),
					Core_4_1(),
					Core_4_2(),
					Core_4_5()
				{
					}
				Context_4_5::Context_4_5(const Handle& handle_):
					Windows::Context_4_4(handle_, EmptyTag()),
					OpenGL::Context_4_5(),
					Core_1_2(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawRangeElements, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexImage3D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexSubImage3D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCopyTexSubImage3D, handle_)
					),
					Core_1_3(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glActiveTexture, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSampleCoverage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCompressedTexImage3D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCompressedTexImage2D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCompressedTexImage1D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCompressedTexSubImage3D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCompressedTexSubImage2D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCompressedTexSubImage1D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetCompressedTexImage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClientActiveTexture, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord1d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord1dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord1f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord1fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord1i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord1iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord1s, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord1sv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord2d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord2dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord2f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord2fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord2i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord2iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord2s, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord2sv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord3d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord3dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord3f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord3fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord3i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord3iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord3s, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord3sv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord4d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord4dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord4f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord4fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord4i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord4iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord4s, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoord4sv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glLoadTransposeMatrixf, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glLoadTransposeMatrixd, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultTransposeMatrixf, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultTransposeMatrixd, handle_)
					),
					Core_1_4(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBlendFuncSeparate, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiDrawArrays, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiDrawElements, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glPointParameterf, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glPointParameterfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glPointParameteri, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glPointParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFogCoordf, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFogCoordfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFogCoordd, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFogCoorddv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFogCoordPointer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3b, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3bv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3s, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3sv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3ub, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3ubv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3us, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColor3usv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColorPointer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos2d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos2dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos2f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos2fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos2i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos2iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos2s, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos2sv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos3d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos3dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos3f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos3fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos3i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos3iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos3s, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWindowPos3sv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBlendColor, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBlendEquation, handle_)
					),
					Core_1_5(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGenQueries, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDeleteQueries, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glIsQuery, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBeginQuery, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glEndQuery, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetQueryiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetQueryObjectiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetQueryObjectuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindBuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDeleteBuffers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGenBuffers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glIsBuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBufferData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBufferSubData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetBufferSubData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMapBuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUnmapBuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetBufferParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetBufferPointerv, handle_)
					),
					Core_2_0(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBlendEquationSeparate, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawBuffers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glStencilOpSeparate, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glStencilFuncSeparate, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glStencilMaskSeparate, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glAttachShader, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindAttribLocation, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCompileShader, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCreateProgram, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCreateShader, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDeleteProgram, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDeleteShader, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDetachShader, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDisableVertexAttribArray, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glEnableVertexAttribArray, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetActiveAttrib, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetActiveUniform, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetAttachedShaders, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetAttribLocation, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetProgramiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetProgramInfoLog, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetShaderiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetShaderInfoLog, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetShaderSource, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetUniformLocation, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetUniformfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetUniformiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetVertexAttribdv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetVertexAttribfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetVertexAttribiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetVertexAttribPointerv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glIsProgram, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glIsShader, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glLinkProgram, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glShaderSource, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUseProgram, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform1f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform2f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform3f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform4f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform1i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform2i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform3i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform4i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform1fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform2fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform3fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform4fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform1iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform2iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform3iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform4iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix2fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix3fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix4fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glValidateProgram, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib1d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib1dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib1f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib1fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib1s, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib1sv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib2d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib2dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib2f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib2fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib2s, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib2sv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib3d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib3dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib3f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib3fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib3s, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib3sv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4Nbv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4Niv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4Nsv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4Nub, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4Nubv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4Nuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4Nusv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4bv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4s, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4sv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4ubv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttrib4usv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribPointer, handle_)
					),
					Core_2_1(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix2x3fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix3x2fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix2x4fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix4x2fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix3x4fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix4x3fv, handle_)
					),
					Core_3_0(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glColorMaski, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetBooleani_v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetIntegeri_v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glEnablei, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDisablei, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glIsEnabledi, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBeginTransformFeedback, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glEndTransformFeedback, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindBufferRange, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindBufferBase, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTransformFeedbackVaryings, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTransformFeedbackVarying, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClampColor, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBeginConditionalRender, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glEndConditionalRender, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribIPointer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetVertexAttribIiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetVertexAttribIuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI1i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI2i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI3i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI4i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI1ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI2ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI3ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI4ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI1iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI2iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI3iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI4iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI1uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI2uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI3uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI4uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI4bv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI4sv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI4ubv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribI4usv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetUniformuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindFragDataLocation, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetFragDataLocation, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform1ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform2ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform3ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform4ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform1uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform2uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform3uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform4uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexParameterIiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexParameterIuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTexParameterIiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTexParameterIuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearBufferiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearBufferuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearBufferfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearBufferfi, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetStringi, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glIsRenderbuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindRenderbuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDeleteRenderbuffers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGenRenderbuffers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glRenderbufferStorage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetRenderbufferParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glIsFramebuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindFramebuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDeleteFramebuffers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGenFramebuffers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCheckFramebufferStatus, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFramebufferTexture1D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFramebufferTexture2D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFramebufferTexture3D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFramebufferRenderbuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetFramebufferAttachmentParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGenerateMipmap, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBlitFramebuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glRenderbufferStorageMultisample, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFramebufferTextureLayer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMapBufferRange, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFlushMappedBufferRange, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindVertexArray, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDeleteVertexArrays, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGenVertexArrays, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glIsVertexArray, handle_)
					),
					Core_3_1(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawArraysInstanced, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawElementsInstanced, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexBuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glPrimitiveRestartIndex, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCopyBufferSubData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetUniformIndices, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetActiveUniformsiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetActiveUniformName, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetUniformBlockIndex, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetActiveUniformBlockiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetActiveUniformBlockName, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformBlockBinding, handle_)
					),
					Core_3_2(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawElementsBaseVertex, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawRangeElementsBaseVertex, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawElementsInstancedBaseVertex, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiDrawElementsBaseVertex, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProvokingVertex, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFenceSync, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glIsSync, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDeleteSync, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClientWaitSync, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glWaitSync, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetInteger64v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetSynciv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetInteger64i_v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetBufferParameteri64v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFramebufferTexture, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexImage2DMultisample, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexImage3DMultisample, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetMultisamplefv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSampleMaski, handle_)
					),
					Core_3_3(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindFragDataLocationIndexed, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetFragDataIndex, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGenSamplers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDeleteSamplers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glIsSampler, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindSampler, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSamplerParameteri, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSamplerParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSamplerParameterf, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSamplerParameterfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSamplerParameterIiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSamplerParameterIuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetSamplerParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetSamplerParameterIiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetSamplerParameterfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetSamplerParameterIuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glQueryCounter, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetQueryObjecti64v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetQueryObjectui64v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribDivisor, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribP1ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribP1uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribP2ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribP2uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribP3ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribP3uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribP4ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribP4uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexP2ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexP2uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexP3ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexP3uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexP4ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexP4uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexCoordP1ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexCoordP1uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexCoordP2ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexCoordP2uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexCoordP3ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexCoordP3uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexCoordP4ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexCoordP4uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoordP1ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoordP1uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoordP2ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoordP2uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoordP3ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoordP3uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoordP4ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiTexCoordP4uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNormalP3ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNormalP3uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glColorP3ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glColorP3uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glColorP4ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glColorP4uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColorP3ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glSecondaryColorP3uiv, handle_)
					),
					Core_4_0(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMinSampleShading, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBlendEquationi, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBlendEquationSeparatei, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBlendFunci, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBlendFuncSeparatei, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawArraysIndirect, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawElementsIndirect, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform1d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform2d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform3d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform4d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform1dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform2dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform3dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniform4dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix2dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix3dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix4dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix2x3dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix2x4dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix3x2dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix3x4dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix4x2dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformMatrix4x3dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetUniformdv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetSubroutineUniformLocation, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetSubroutineIndex, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetActiveSubroutineUniformiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetActiveSubroutineUniformName, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetActiveSubroutineName, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUniformSubroutinesuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetUniformSubroutineuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetProgramStageiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glPatchParameteri, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glPatchParameterfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindTransformFeedback, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDeleteTransformFeedbacks, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGenTransformFeedbacks, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glIsTransformFeedback, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glPauseTransformFeedback, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glResumeTransformFeedback, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawTransformFeedback, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawTransformFeedbackStream, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBeginQueryIndexed, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glEndQueryIndexed, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetQueryIndexediv, handle_)
					),
					Core_4_1(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glReleaseShaderCompiler, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glShaderBinary, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetShaderPrecisionFormat, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDepthRangef, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearDepthf, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetProgramBinary, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramBinary, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramParameteri, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUseProgramStages, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glActiveShaderProgram, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCreateShaderProgramv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindProgramPipeline, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDeleteProgramPipelines, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGenProgramPipelines, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glIsProgramPipeline, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetProgramPipelineiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform1i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform1iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform1f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform1fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform1d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform1dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform1ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform1uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform2i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform2iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform2f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform2fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform2d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform2dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform2ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform2uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform3i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform3iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform3f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform3fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform3d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform3dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform3ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform3uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform4i, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform4iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform4f, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform4fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform4d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform4dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform4ui, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniform4uiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix2fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix3fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix4fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix2dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix3dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix4dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix2x3fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix3x2fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix2x4fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix4x2fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix3x4fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix4x3fv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix2x3dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix3x2dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix2x4dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix4x2dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix3x4dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glProgramUniformMatrix4x3dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glValidateProgramPipeline, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetProgramPipelineInfoLog, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribL1d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribL2d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribL3d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribL4d, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribL1dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribL2dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribL3dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribL4dv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribLPointer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetVertexAttribLdv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glViewportArrayv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glViewportIndexedf, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glViewportIndexedfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glScissorArrayv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glScissorIndexed, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glScissorIndexedv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDepthRangeArrayv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDepthRangeIndexed, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetFloati_v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetDoublei_v, handle_)
					),
					Core_4_2(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawArraysInstancedBaseInstance, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawElementsInstancedBaseInstance, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawElementsInstancedBaseVertexBaseInstance, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetInternalformativ, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetActiveAtomicCounterBufferiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindImageTexture, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMemoryBarrier, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexStorage1D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexStorage2D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexStorage3D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawTransformFeedbackInstanced, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDrawTransformFeedbackStreamInstanced, handle_)
					),
					Core_4_3(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearBufferData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearBufferSubData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDispatchCompute, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDispatchComputeIndirect, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCopyImageSubData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFramebufferParameteri, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetFramebufferParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetInternalformati64v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glInvalidateTexSubImage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glInvalidateTexImage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glInvalidateBufferSubData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glInvalidateBufferData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glInvalidateFramebuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glInvalidateSubFramebuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiDrawArraysIndirect, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMultiDrawElementsIndirect, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetProgramInterfaceiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetProgramResourceIndex, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetProgramResourceName, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetProgramResourceiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetProgramResourceLocation, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetProgramResourceLocationIndex, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glShaderStorageBlockBinding, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexBufferRange, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexStorage2DMultisample, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTexStorage3DMultisample, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureView, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindVertexBuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribFormat, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribIFormat, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribLFormat, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexAttribBinding, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexBindingDivisor, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDebugMessageControl, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDebugMessageInsert, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDebugMessageCallback, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetDebugMessageLog, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glPushDebugGroup, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glPopDebugGroup, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glObjectLabel, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetObjectLabel, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glObjectPtrLabel, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetObjectPtrLabel, handle_)
					),
					Core_4_4(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBufferStorage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearTexImage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearTexSubImage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindBuffersBase, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindBuffersRange, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindTextures, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindSamplers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindImageTextures, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindVertexBuffers, handle_)
					),
					Core_4_5(
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClipControl, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCreateTransformFeedbacks, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTransformFeedbackBufferBase, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTransformFeedbackBufferRange, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTransformFeedbackiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTransformFeedbacki_v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTransformFeedbacki64_v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCreateBuffers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNamedBufferStorage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNamedBufferData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNamedBufferSubData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCopyNamedBufferSubData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearNamedBufferData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearNamedBufferSubData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMapNamedBuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMapNamedBufferRange, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glUnmapNamedBuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glFlushMappedNamedBufferRange, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetNamedBufferParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetNamedBufferParameteri64v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetNamedBufferPointerv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetNamedBufferSubData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCreateFramebuffers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNamedFramebufferRenderbuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNamedFramebufferParameteri, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNamedFramebufferTexture, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNamedFramebufferTextureLayer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNamedFramebufferDrawBuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNamedFramebufferDrawBuffers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNamedFramebufferReadBuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glInvalidateNamedFramebufferData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glInvalidateNamedFramebufferSubData, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearNamedFramebufferiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearNamedFramebufferuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearNamedFramebufferfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glClearNamedFramebufferfi, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBlitNamedFramebuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCheckNamedFramebufferStatus, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetNamedFramebufferParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetNamedFramebufferAttachmentParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCreateRenderbuffers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNamedRenderbufferStorage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glNamedRenderbufferStorageMultisample, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetNamedRenderbufferParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCreateTextures, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureBuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureBufferRange, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureStorage1D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureStorage2D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureStorage3D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureStorage2DMultisample, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureStorage3DMultisample, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureSubImage1D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureSubImage2D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureSubImage3D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCompressedTextureSubImage1D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCompressedTextureSubImage2D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCompressedTextureSubImage3D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCopyTextureSubImage1D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCopyTextureSubImage2D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCopyTextureSubImage3D, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureParameterf, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureParameterfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureParameteri, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureParameterIiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureParameterIuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGenerateTextureMipmap, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glBindTextureUnit, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTextureImage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetCompressedTextureImage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTextureLevelParameterfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTextureLevelParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTextureParameterfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTextureParameterIiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTextureParameterIuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTextureParameteriv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCreateVertexArrays, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glDisableVertexArrayAttrib, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glEnableVertexArrayAttrib, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexArrayElementBuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexArrayVertexBuffer, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexArrayVertexBuffers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexArrayAttribBinding, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexArrayAttribFormat, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexArrayAttribIFormat, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexArrayAttribLFormat, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glVertexArrayBindingDivisor, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetVertexArrayiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetVertexArrayIndexediv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetVertexArrayIndexed64iv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCreateSamplers, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCreateProgramPipelines, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glCreateQueries, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetQueryBufferObjecti64v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetQueryBufferObjectiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetQueryBufferObjectui64v, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetQueryBufferObjectuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glMemoryBarrierByRegion, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetTextureSubImage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetCompressedTextureSubImage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetGraphicsResetStatus, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnCompressedTexImage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnTexImage, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnUniformdv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnUniformfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnUniformiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnUniformuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glReadnPixels, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnMapdv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnMapfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnMapiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnPixelMapfv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnPixelMapuiv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnPixelMapusv, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnPolygonStipple, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnColorTable, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnConvolutionFilter, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnSeparableFilter, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnHistogram, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glGetnMinmax, handle_),
					__GREAT_V_ENGINE_2__GET_PROCEDURE_ADDRESS2__(glTextureBarrier, handle_)
					)
				{
					MakeCurrent(nullptr, nullptr);
				}
				Context_4_5::Context_4_5(const DeviceContextHandle& deviceContextHandle_):
					Context_4_5(MakeCurrentAndReturn(deviceContextHandle_, ObtainHandle(deviceContextHandle_, nullptr, GetAttributes())))
				{
				}
#pragma endregion
			}
#endif
		}
	}
}


#pragma region
#pragma endregion


